name: cardano_wallet_reader
description: ARC Homework - Web3 Mobile Integration class
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  device_preview: ^1.3.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^9.0.5
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
